// Generated by gencpp from file just_move/control.msg
// DO NOT EDIT!


#ifndef JUST_MOVE_MESSAGE_CONTROL_H
#define JUST_MOVE_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace just_move
{
template <class ContainerAllocator>
struct control_
{
  typedef control_<ContainerAllocator> Type;

  control_()
    : control_message()
    , distance(0.0)  {
    }
  control_(const ContainerAllocator& _alloc)
    : control_message(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _control_message_type;
  _control_message_type control_message;

   typedef double _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::just_move::control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::just_move::control_<ContainerAllocator> const> ConstPtr;

}; // struct control_

typedef ::just_move::control_<std::allocator<void> > control;

typedef boost::shared_ptr< ::just_move::control > controlPtr;
typedef boost::shared_ptr< ::just_move::control const> controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::just_move::control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::just_move::control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace just_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'just_move': ['/home/robot/catkin_ws/src/just_move/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::just_move::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::just_move::control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::just_move::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::just_move::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_move::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_move::control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::just_move::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9d4f3ee22249204d59eaaa853bc7feb";
  }

  static const char* value(const ::just_move::control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9d4f3ee22249204ULL;
  static const uint64_t static_value2 = 0xd59eaaa853bc7febULL;
};

template<class ContainerAllocator>
struct DataType< ::just_move::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "just_move/control";
  }

  static const char* value(const ::just_move::control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::just_move::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string control_message\n\
float64 distance\n\
\n\
";
  }

  static const char* value(const ::just_move::control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::just_move::control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_message);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::just_move::control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::just_move::control_<ContainerAllocator>& v)
  {
    s << indent << "control_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.control_message);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUST_MOVE_MESSAGE_CONTROL_H
