// Generated by gencpp from file just_move/moveRequest.msg
// DO NOT EDIT!


#ifndef JUST_MOVE_MESSAGE_MOVEREQUEST_H
#define JUST_MOVE_MESSAGE_MOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace just_move
{
template <class ContainerAllocator>
struct moveRequest_
{
  typedef moveRequest_<ContainerAllocator> Type;

  moveRequest_()
    : control_message()  {
    }
  moveRequest_(const ContainerAllocator& _alloc)
    : control_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _control_message_type;
  _control_message_type control_message;




  typedef boost::shared_ptr< ::just_move::moveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::just_move::moveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct moveRequest_

typedef ::just_move::moveRequest_<std::allocator<void> > moveRequest;

typedef boost::shared_ptr< ::just_move::moveRequest > moveRequestPtr;
typedef boost::shared_ptr< ::just_move::moveRequest const> moveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::just_move::moveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::just_move::moveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace just_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'just_move': ['/home/robot/catkin_ws/src/just_move/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::just_move::moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::just_move::moveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::just_move::moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::just_move::moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_move::moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::just_move::moveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::just_move::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c245e0bd1b1b0a736889ca9b4626bcb3";
  }

  static const char* value(const ::just_move::moveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc245e0bd1b1b0a73ULL;
  static const uint64_t static_value2 = 0x6889ca9b4626bcb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::just_move::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "just_move/moveRequest";
  }

  static const char* value(const ::just_move::moveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::just_move::moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string control_message\n\
";
  }

  static const char* value(const ::just_move::moveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::just_move::moveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::just_move::moveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::just_move::moveRequest_<ContainerAllocator>& v)
  {
    s << indent << "control_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.control_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUST_MOVE_MESSAGE_MOVEREQUEST_H
