// Generated by gencpp from file just_move/move.msg
// DO NOT EDIT!


#ifndef JUST_MOVE_MESSAGE_MOVE_H
#define JUST_MOVE_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <just_move/moveRequest.h>
#include <just_move/moveResponse.h>


namespace just_move
{

struct move
{

typedef moveRequest Request;
typedef moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move
} // namespace just_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::just_move::move > {
  static const char* value()
  {
    return "e3e06edf159d0eb6dd04caf49ff1b9fb";
  }

  static const char* value(const ::just_move::move&) { return value(); }
};

template<>
struct DataType< ::just_move::move > {
  static const char* value()
  {
    return "just_move/move";
  }

  static const char* value(const ::just_move::move&) { return value(); }
};


// service_traits::MD5Sum< ::just_move::moveRequest> should match 
// service_traits::MD5Sum< ::just_move::move > 
template<>
struct MD5Sum< ::just_move::moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::just_move::move >::value();
  }
  static const char* value(const ::just_move::moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::just_move::moveRequest> should match 
// service_traits::DataType< ::just_move::move > 
template<>
struct DataType< ::just_move::moveRequest>
{
  static const char* value()
  {
    return DataType< ::just_move::move >::value();
  }
  static const char* value(const ::just_move::moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::just_move::moveResponse> should match 
// service_traits::MD5Sum< ::just_move::move > 
template<>
struct MD5Sum< ::just_move::moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::just_move::move >::value();
  }
  static const char* value(const ::just_move::moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::just_move::moveResponse> should match 
// service_traits::DataType< ::just_move::move > 
template<>
struct DataType< ::just_move::moveResponse>
{
  static const char* value()
  {
    return DataType< ::just_move::move >::value();
  }
  static const char* value(const ::just_move::moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JUST_MOVE_MESSAGE_MOVE_H
